spring:
  application:
    name: kacosmetology-api
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/kacosmetology
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date-time: iso
      date: iso
      time: iso
  data:
    redis:
      url: jdbc:redis://localhost:6379/
      username: redis
      password: password

jwt:
  key: ${JWT_KEY:d8c734c4c857d845f3d0fa214d5c6017ea653646ca6f4256bef09aa5477f93ce}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000
server:
  port: 8080
